targets:
  arangodb:
    module: arangodb
    endpoint: http://arango.default:8529
    database: _system
    username: root
    password: root
  yugabyte_sql:
    module: postgres
    # options for YugabyteDB relevant (and faster) for an IoT ingest workload:
    #  yb_enable_expression_pushdown=on may help for queries and is off by default only for rolling upgrades
    #  yb_enable_upsert_mode=on does not read before write and on duplicate key, updates it rather than raise an error.
    #  yb_disable_transactional_writes=on is similar to autocommit each rows, and uses a fast-path insert
    connection_string: "host=yb-tservers.default port=5433 dbname=postgres user=yugabyte options='-c yb_enable_expression_pushdown=on -c yb_enable_upsert_mode=on -c yb_disable_transactional_writes=on'"
    # Yugabyte needs this extension for the gen_random_uuid function
    install_extensions: pgcrypto
  yugabyte_cql:
    module: cassandra
    contact_points: "yb-tservers.default"
    keyspace: "benchmark"
    replication_factor: 3
    consistency_level: "LOCAL_QUORUM"
    max_sync_calls: 1
    device_spread: 1
  cockroachdb:
    module: postgres
    connection_string: "host=cockroachdb-public.default.svc.cluster.local port=26257 dbname=postgres"
  postgresql:
    module: postgres
    connection_string: "host=postgres-postgresql.default port=5432 dbname=postgres user=postgres password=postgres"
  cassandra_sync:
    module: cassandra
    contact_points: "k8ssandra-dc1-service"
    keyspace: "benchmark"
    replication_factor: 3
    consistency_level: "LOCAL_QUORUM"
    max_sync_calls: 1
    device_spread: 1
  cassandra_async:
    module: cassandra
    contact_points: "k8ssandra-dc1-service"
    keyspace: "benchmark"
    replication_factor: 3
    consistency_level: "LOCAL_QUORUM"
    max_sync_calls: 120
    device_spread: 1
  influxdb:
    module: influxdb
    endpoint: "http://influxdb-influxdb2.default.svc.cluster.local"
    org: influxdata
    token: 1234admin1234
    device_spread: 1
  timescaledb:
    module: timescaledb
    connection_string: "host=timescaledb.default.svc.cluster.local port=5432 dbname=postgres user=postgres password=postgres"
  elasticsearch:
    module: elasticsearch
    endpoint: https://elastic-es-http.default.svc.cluster.local:9200
  azure_data_explorer:
    module: azure_data_explorer
    kusto_uri: https://adxcompare.westeurope.kusto.windows.net
    kusto_ingest_uri: https://ingest-adxcompare.westeurope.kusto.windows.net
    kusto_db: SampleDB
namespace: default
