apiVersion: batch/v1
kind: Job
metadata:
  name: dbtest-worker
  namespace: {{ .Values.namespace }}
spec:
  parallelism: {{ .Values.workers }}
  completions: {{ .Values.workers }}
  template:
    metadata:
      labels:
        app: dbtest-worker
    spec:
      containers:
      - name: worker
        resources:
            requests:
              memory: 4G
              cpu: 1
            limits:
              memory: 4G
              cpu: 1
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: TEST_MODULE
          value: "{{ .Values.target_module }}"
        - name: RUN_CONFIG
          value: "{{ .Values.run_config }}"
        - name: INSTANCE_TYPE
          value: "worker"
        - name: WORKER_COUNT
          value: "{{ .Values.workers }}"
        - name: COLLECTOR_URL
          value: "http://dbtest-collector:5000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: adx-secret
      restartPolicy: Never
      terminationGracePeriodSeconds: 2
      nodeSelector:
{{ .Values.nodeSelector | toYaml | indent 8 }}
  backoffLimit: 0
